CREATE TABLE SV900M 
(
  Q_CODE NUMBER(10, 0) NOT NULL 
, Q_TEXT LONG NOT NULL 
, Q_TITLE VARCHAR2(200 BYTE) NOT NULL 
, Q_EXPL VARCHAR2(500 BYTE) 
, CONSTRAINT SV900M_PK PRIMARY KEY 
  (
    Q_CODE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SV900M_PK ON SV900M (Q_CODE ASC) 
      LOGGING 
      TABLESPACE USERDATA 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERDATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

COMMENT ON TABLE SV900M IS '쿼리';

COMMENT ON COLUMN SV900M.Q_CODE IS '쿼리코드';

COMMENT ON COLUMN SV900M.Q_TEXT IS '쿼리';

COMMENT ON COLUMN SV900M.Q_TITLE IS '쿼리제목';

COMMENT ON COLUMN SV900M.Q_EXPL IS '쿼리설명';


---------------------------------
CREATE TABLE SV901M 
(
  Q_CODE NUMBER(10, 0) NOT NULL 
, ORG_ID VARCHAR2(10 BYTE) NOT NULL 
, CONSTRAINT SV901M_PK PRIMARY KEY 
  (
    Q_CODE 
  , ORG_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SV901M_PK ON SV901M (Q_CODE ASC, ORG_ID ASC) 
      LOGGING 
      TABLESPACE USERDATA 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERDATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE SV901M
ADD CONSTRAINT SV901M_FK1 FOREIGN KEY
(
  Q_CODE 
)
REFERENCES SV900M
(
  Q_CODE 
)
ON DELETE CASCADE ENABLE;

COMMENT ON COLUMN SV901M.Q_CODE IS '쿼리코드
';

COMMENT ON COLUMN SV901M.ORG_ID IS '그룹코드
';


-------------------------
CREATE TABLE SV902M 
(
  ID NUMBER NOT NULL 
, Q_CODE NUMBER(10, 0) NOT NULL 
, HUSR_ID VARCHAR2(7 BYTE) NOT NULL 
, REQ_DT DATE NOT NULL 
, REQ_PUR VARCHAR2(100 BYTE) 
, CONSTRAINT SV902M_PK PRIMARY KEY 
  (
    ID 
  , Q_CODE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SV902M_PK ON SV902M (ID ASC, Q_CODE ASC) 
      LOGGING 
      TABLESPACE USERDATA 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERDATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE SV902M
ADD CONSTRAINT SV902M_FK1 FOREIGN KEY
(
  Q_CODE 
)
REFERENCES SV900M
(
  Q_CODE 
)
ENABLE;

COMMENT ON COLUMN SV902M.Q_CODE IS '쿼리코드';

COMMENT ON COLUMN SV902M.HUSR_ID IS '구성원ID';

COMMENT ON COLUMN SV902M.REQ_DT IS '요청일자';

COMMENT ON COLUMN SV902M.REQ_PUR IS '요청목적';


